

% d2vx_dy(2:end-1,:) = (...
%                     dvx_dy(2:end-1,:).*sign(v_y(2:end-1,:)).* ...
%                                      (is_fluid(1:end-2,:) - sign(v_y(2:end-1,:))  ~= -1).* ...
%                                      (is_fluid(3:end,:)   + sign(v_y(2:end-1,:))  ~= -1)...
%                   - dvx_dy(1:end-2,:).*(sign(v_y(2:end-1,:)) ==  1).*is_fluid(1:end-2,:) ...
%                   + dvx_dy(3:end,:  ).*(sign(v_y(2:end-1,:)) == -1).*is_fluid(3:end,:  ) ...
%                     )/dy;
% d2vy_dx(:,2:end-1) = (...
%                     dvy_dx(:,2:end-1).*sign(v_x(:,2:end-1)).* ...
%                                      (is_fluid(:,1:end-2) - sign(v_x(:,2:end-1))  ~= -1).* ...
%                                      (is_fluid(:,3:end)   + sign(v_x(:,2:end-1))  ~= -1)...
%                   - dvy_dx(:,1:end-2).*(sign(v_x(:,2:end-1)) ==  1).*is_fluid(:,1:end-2) ...
%                   + dvy_dx(:,3:end  ).*(sign(v_x(:,2:end-1)) == -1).*is_fluid(:,3:end  ) ...
%                     )/dx;
% 
% 

d2vx_dy(3:end-2,:) = ((v_x_centered(5:end  ,:)*0.4  ...
                     + v_x_centered(4:end-1,:)*0.6)*0.5  ...
                     - v_x_centered(3:end-2,:)*1     ...
                     +(v_x_centered(2:end-3,:)*0.6  ...
                     + v_x_centered(1:end-4,:)*0.4)*0.5)./dy^2;

d2vy_dx(:,3:end-2) = ((v_y_centered(:,5:end  )*0.4  ...
                     + v_y_centered(:,4:end-1)*0.6)*0.5  ...
                     - v_y_centered(:,3:end-2)*1     ...
                     +(v_y_centered(:,2:end-3)*0.6  ...
                     + v_y_centered(:,1:end-4)*0.4)*0.5)./dx^2;


v_x_centered =  (v_x_centered + dt*d2vx_dy*viscosity_constant/density).*is_fluid;
v_y_centered =  (v_y_centered + dt*d2vy_dx*viscosity_constant/density).*is_fluid;


